// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStF2SUX7821XOO0-dOEFbHIuzBqar2q0',
    appId: '1:65552918554:web:ae666bc62438cea81e89a3',
    messagingSenderId: '65552918554',
    projectId: 'life-bookshelf-1fea6',
    authDomain: 'life-bookshelf-1fea6.firebaseapp.com',
    storageBucket: 'life-bookshelf-1fea6.appspot.com',
    measurementId: 'G-02LKBR0KF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2U1iiWjIk2BOtoSacSVm0QUfO2-SqOc',
    appId: '1:65552918554:android:f5775c975743e31c1e89a3',
    messagingSenderId: '65552918554',
    projectId: 'life-bookshelf-1fea6',
    storageBucket: 'life-bookshelf-1fea6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrC0eOWGRtJj_tivNTV7FPn9ozItpX38M',
    appId: '1:65552918554:ios:a569b3eb507d1e5e1e89a3',
    messagingSenderId: '65552918554',
    projectId: 'life-bookshelf-1fea6',
    storageBucket: 'life-bookshelf-1fea6.appspot.com',
    iosBundleId: 'life-bookshelf',
  );
}
